### ISSUE TITLE
Smooth render

### ISSUE THREAD

**Issue by RelTakeover** [ZfsrGhS953/Petridish-Ogar#3]
you can do the smooth render effect like agar.io ?

**Comment by ZfsrGhS953** [comment]
It already exists.

**Comment by RelTakeover** [comment]
how to activate?

**Comment by RelTakeover** [comment]
or where i can change to activae effect?

**Comment by ZfsrGhS953** [comment]
https://github.com/ZfsrGhS953/Petridish-Ogar/blob/master/client/index.html#L4940

**Comment by RelTakeover** [comment]
what i should change to activate?

**Comment by RelTakeover** [comment]
![image](https://cloud.githubusercontent.com/assets/19374681/19974895/d461609e-a1c8-11e6-9fe5-e2daa481f417.png)

THIS EFFECT IS BUGGY , NOT LIKE AGAR.IO :(

**Comment by ZfsrGhS953** [comment]
You can set smooth render to on when zoom is high, like this:

``` javascript
if (ratio < 0.4) {
isSimpleMode = true;
} else {
isSimpleMode = false;
}
```

The (0.4) is the zoom level where the cellborders get buggy.
