### ISSUE TITLE
CLIENT

### ISSUE THREAD

**Issue by RelTakeover** [ZfsrGhS953/Petridish-Ogar#7]
THE OGARUL CLIENT NOT WORKING SKINS WITH MULTIOGAR-EDITED OF MEGABYTE :( WHY

**Comment by ZfsrGhS953** [comment]
Ogar Unlimited client uses protocol 4, which doesn't support custom skins of MultiOgar-Edited. They are only supported for protocols 5 and 6. This is off-topic (please post in https://github.com/AJS-development/OgarUL-Client/issues and https://github.com/Megabyte918/MultiOgar-Edited/issues ), so I'll close this issue.
