### ISSUE TITLE
please..

### ISSUE THREAD

**Issue by RelTakeover** [ZfsrGhS953/Petridish-Ogar#8]
i have a problem with ogarUL-CLIENT , that client is not compatible with multiogar-edited ( i mean to skins) , you can update to protocol 5 or 6 please , i cant use cigar's client because is soooo laggy

**Comment by ZfsrGhS953** [comment]
Duplicate of #7 . I don't own neither MultiOgar-Edited nor OgarUL-Client so I can't update/fix them.
