### ISSUE TITLE
ZfsrGhS953

### ISSUE THREAD

**Issue by RelTakeover** [ZfsrGhS953/Petridish-Ogar#9]
Hello you are a nice programmer you can create a public code for private servers , that you can set the name of the clan above of the name like clan-word extension using ogarUL CLIENT 

![image](https://cloud.githubusercontent.com/assets/19374681/20246845/7580799c-a99e-11e6-9c88-1775b9640f30.png)

**Comment by ZfsrGhS953** [comment]
I can't, because I don't own Ogar Unlimited client.

**Comment by RelTakeover** [comment]
or public script? please for my game http://ogar.pw pleasee
